[package]
name = "molt-sample"
version = "0.3.0"
authors = ["wduquette <will@wjduquette.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
molt = "0.3.0"
molt-shell = "0.3.0"
